import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/AuthContext";
import { AuthModalProvider } from "./context/AuthModalContext";
import AuthModal from "./components/UI/AuthModal";
import { Toaster } from "sonner";
import { GuestProvider } from "./context/GuestContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Summarist",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div id="app-root">
          <Toaster richColors position="top-right" />
          <GuestProvider>
            <AuthProvider>
              <AuthModalProvider>
                {children}
                <AuthModal />
              </AuthModalProvider>
            </AuthProvider>
          </GuestProvider>
        </div>
      </body>
    </html>
  );
}
